#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SSJ2_Workout.Droid.Resource", IsApplication=true)]

namespace SSJ2_Workout.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F02000F
			public const int back51 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int backBMI = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int backFood = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int backFoodEat = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int backGoals = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int backMenu = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int backNotify = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int backPulse = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int backSettings = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int backw = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int banner = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int bannerStoper = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int berserk1 = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int berserk2 = 2130837532;
			
			// aapt resource value: 0x7F020000
			public const int BodyIcon = 2130837504;
			
			// aapt resource value: 0x7F02001D
			public const int deathnote = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int evangelion = 2130837534;
			
			// aapt resource value: 0x7F020001
			public const int GoalsIcon = 2130837505;
			
			// aapt resource value: 0x7F02001F
			public const int gta = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int iconUnderWork = 2130837536;
			
			// aapt resource value: 0x7F020002
			public const int KcalIcon = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int KoszButton = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int KoszButton2 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int LocalIcon = 2130837509;
			
			// aapt resource value: 0x7F020021
			public const int menuICON = 2130837537;
			
			// aapt resource value: 0x7F020006
			public const int NotifyIcon = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int PlusButton = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int PlusButton2 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int PulseIcon = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int RB = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int SettingsIcon = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int StatIcon = 2130837516;
			
			// aapt resource value: 0x7F020022
			public const int stepsCAT = 2130837538;
			
			// aapt resource value: 0x7F02000D
			public const int StepsIcon = 2130837517;
			
			// aapt resource value: 0x7F020023
			public const int stoperIcon = 2130837539;
			
			// aapt resource value: 0x7F02000E
			public const int Zawarudo = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030001
			public const int icon = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int icon_round = 2130903042;
			
			// aapt resource value: 0x7F030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7F030003
			public const int launcher_foreground = 2130903043;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
